# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: personnel.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fpersonnel.proto\x12\tpersonnel\"\x7f\n\x08Retailer\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x15\n\rbusiness_name\x18\x03 \x01(\t\x12\x15\n\rbusiness_type\x18\x04 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x05 \x01(\t\x12\x16\n\x0e\x63lassification\x18\x06 \x01(\t\"(\n\x1aGetRetailerByUserIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"D\n\x1bGetRetailerByUserIdResponse\x12%\n\x08retailer\x18\x01 \x01(\x0b\x32\x13.personnel.Retailer2z\n\x10PersonnelService\x12\x66\n\x13GetRetailerByUserId\x12%.personnel.GetRetailerByUserIdRequest\x1a&.personnel.GetRetailerByUserIdResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'personnel_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RETAILER._serialized_start=30
  _RETAILER._serialized_end=157
  _GETRETAILERBYUSERIDREQUEST._serialized_start=159
  _GETRETAILERBYUSERIDREQUEST._serialized_end=199
  _GETRETAILERBYUSERIDRESPONSE._serialized_start=201
  _GETRETAILERBYUSERIDRESPONSE._serialized_end=269
  _PERSONNELSERVICE._serialized_start=271
  _PERSONNELSERVICE._serialized_end=393
# @@protoc_insertion_point(module_scope)
