# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from booosta_proto.py_grpc import order_pb2 as order__pb2


class OrderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOrderById = channel.unary_unary(
                '/order.OrderService/GetOrderById',
                request_serializer=order__pb2.GetOrderByIdRequest.SerializeToString,
                response_deserializer=order__pb2.GetOrderByIdResponse.FromString,
                )
        self.GetOrderItemById = channel.unary_unary(
                '/order.OrderService/GetOrderItemById',
                request_serializer=order__pb2.GetOrderItemByIdRequest.SerializeToString,
                response_deserializer=order__pb2.GetOrderItemByIdResponse.FromString,
                )
        self.GetOrderItemsByProductId = channel.unary_unary(
                '/order.OrderService/GetOrderItemsByProductId',
                request_serializer=order__pb2.GetOrderItemsByProductIdRequest.SerializeToString,
                response_deserializer=order__pb2.OrderItemsListResponse.FromString,
                )
        self.GetCustomerById = channel.unary_unary(
                '/order.OrderService/GetCustomerById',
                request_serializer=order__pb2.GetCustomerByIdRequest.SerializeToString,
                response_deserializer=order__pb2.GetCustomerByIdResponse.FromString,
                )
        self.GetOrderItemQuantityByProductId = channel.unary_unary(
                '/order.OrderService/GetOrderItemQuantityByProductId',
                request_serializer=order__pb2.GetOrderItemQuantityByProductIdRequest.SerializeToString,
                response_deserializer=order__pb2.GetOrderItemQuantityByProductIdResponse.FromString,
                )
        self.GetOrderItemsByCreatedById = channel.unary_unary(
                '/order.OrderService/GetOrderItemsByCreatedById',
                request_serializer=order__pb2.GetOrderItemsByCreatedByIdRequest.SerializeToString,
                response_deserializer=order__pb2.OrderItemsListResponse.FromString,
                )
        self.GetOrderByCreatedByIdAndPaymentType = channel.unary_unary(
                '/order.OrderService/GetOrderByCreatedByIdAndPaymentType',
                request_serializer=order__pb2.GetOrderByCreatedByIdAndPaymentTypeRequest.SerializeToString,
                response_deserializer=order__pb2.GetOrderByCreatedByIdAndPaymentTypeResponse.FromString,
                )
        self.GetOrderItemsByProductIdAndCreatedById = channel.unary_unary(
                '/order.OrderService/GetOrderItemsByProductIdAndCreatedById',
                request_serializer=order__pb2.GetOrderItemsByProductIdAndCreatedByIdRequest.SerializeToString,
                response_deserializer=order__pb2.OrderItemsListResponse.FromString,
                )
        self.GetAllOrderItems = channel.unary_unary(
                '/order.OrderService/GetAllOrderItems',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=order__pb2.OrderItemsListResponse.FromString,
                )
        self.GetAllCustomers = channel.unary_unary(
                '/order.OrderService/GetAllCustomers',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=order__pb2.CustomerListResponse.FromString,
                )
        self.GetCustomersByCreatedBy = channel.unary_unary(
                '/order.OrderService/GetCustomersByCreatedBy',
                request_serializer=order__pb2.GetCustomersByCreatedByRequest.SerializeToString,
                response_deserializer=order__pb2.GetCustomersByCreatedByResponse.FromString,
                )
        self.GetOrderItemsByOrderId = channel.unary_unary(
                '/order.OrderService/GetOrderItemsByOrderId',
                request_serializer=order__pb2.GetOrderItemsByOrderIdRequest.SerializeToString,
                response_deserializer=order__pb2.OrderItemsListResponse.FromString,
                )
        self.UpdateOrderById = channel.unary_unary(
                '/order.OrderService/UpdateOrderById',
                request_serializer=order__pb2.UpdateOrderByIdRequest.SerializeToString,
                response_deserializer=order__pb2.UpdateOrderByIdResponse.FromString,
                )
        self.RemoveProductFromCartByProductId = channel.unary_unary(
                '/order.OrderService/RemoveProductFromCartByProductId',
                request_serializer=order__pb2.RemoveProductFromCartByProductIdRequest.SerializeToString,
                response_deserializer=order__pb2.RemoveProductFromCartByProductIdResponse.FromString,
                )
        self.GetCustomerDebtById = channel.unary_unary(
                '/order.OrderService/GetCustomerDebtById',
                request_serializer=order__pb2.GetCustomerDebtByIdRequest.SerializeToString,
                response_deserializer=order__pb2.GetCustomerDebtByIdResponse.FromString,
                )
        self.UpdateCustomerDebtById = channel.unary_unary(
                '/order.OrderService/UpdateCustomerDebtById',
                request_serializer=order__pb2.UpdateCustomerDebtByIdRequest.SerializeToString,
                response_deserializer=order__pb2.UpdateCustomerDebtByIdResponse.FromString,
                )
        self.GetCartByProductId = channel.unary_unary(
                '/order.OrderService/GetCartByProductId',
                request_serializer=order__pb2.GetCartByProductIdRequest.SerializeToString,
                response_deserializer=order__pb2.GetCartByProductIdResponse.FromString,
                )


class OrderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetOrderById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderItemById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderItemsByProductId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCustomerById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderItemQuantityByProductId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderItemsByCreatedById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderByCreatedByIdAndPaymentType(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderItemsByProductIdAndCreatedById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllOrderItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllCustomers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCustomersByCreatedBy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderItemsByOrderId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateOrderById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveProductFromCartByProductId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCustomerDebtById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCustomerDebtById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCartByProductId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOrderById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderById,
                    request_deserializer=order__pb2.GetOrderByIdRequest.FromString,
                    response_serializer=order__pb2.GetOrderByIdResponse.SerializeToString,
            ),
            'GetOrderItemById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderItemById,
                    request_deserializer=order__pb2.GetOrderItemByIdRequest.FromString,
                    response_serializer=order__pb2.GetOrderItemByIdResponse.SerializeToString,
            ),
            'GetOrderItemsByProductId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderItemsByProductId,
                    request_deserializer=order__pb2.GetOrderItemsByProductIdRequest.FromString,
                    response_serializer=order__pb2.OrderItemsListResponse.SerializeToString,
            ),
            'GetCustomerById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCustomerById,
                    request_deserializer=order__pb2.GetCustomerByIdRequest.FromString,
                    response_serializer=order__pb2.GetCustomerByIdResponse.SerializeToString,
            ),
            'GetOrderItemQuantityByProductId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderItemQuantityByProductId,
                    request_deserializer=order__pb2.GetOrderItemQuantityByProductIdRequest.FromString,
                    response_serializer=order__pb2.GetOrderItemQuantityByProductIdResponse.SerializeToString,
            ),
            'GetOrderItemsByCreatedById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderItemsByCreatedById,
                    request_deserializer=order__pb2.GetOrderItemsByCreatedByIdRequest.FromString,
                    response_serializer=order__pb2.OrderItemsListResponse.SerializeToString,
            ),
            'GetOrderByCreatedByIdAndPaymentType': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderByCreatedByIdAndPaymentType,
                    request_deserializer=order__pb2.GetOrderByCreatedByIdAndPaymentTypeRequest.FromString,
                    response_serializer=order__pb2.GetOrderByCreatedByIdAndPaymentTypeResponse.SerializeToString,
            ),
            'GetOrderItemsByProductIdAndCreatedById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderItemsByProductIdAndCreatedById,
                    request_deserializer=order__pb2.GetOrderItemsByProductIdAndCreatedByIdRequest.FromString,
                    response_serializer=order__pb2.OrderItemsListResponse.SerializeToString,
            ),
            'GetAllOrderItems': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllOrderItems,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=order__pb2.OrderItemsListResponse.SerializeToString,
            ),
            'GetAllCustomers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllCustomers,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=order__pb2.CustomerListResponse.SerializeToString,
            ),
            'GetCustomersByCreatedBy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCustomersByCreatedBy,
                    request_deserializer=order__pb2.GetCustomersByCreatedByRequest.FromString,
                    response_serializer=order__pb2.GetCustomersByCreatedByResponse.SerializeToString,
            ),
            'GetOrderItemsByOrderId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderItemsByOrderId,
                    request_deserializer=order__pb2.GetOrderItemsByOrderIdRequest.FromString,
                    response_serializer=order__pb2.OrderItemsListResponse.SerializeToString,
            ),
            'UpdateOrderById': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateOrderById,
                    request_deserializer=order__pb2.UpdateOrderByIdRequest.FromString,
                    response_serializer=order__pb2.UpdateOrderByIdResponse.SerializeToString,
            ),
            'RemoveProductFromCartByProductId': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveProductFromCartByProductId,
                    request_deserializer=order__pb2.RemoveProductFromCartByProductIdRequest.FromString,
                    response_serializer=order__pb2.RemoveProductFromCartByProductIdResponse.SerializeToString,
            ),
            'GetCustomerDebtById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCustomerDebtById,
                    request_deserializer=order__pb2.GetCustomerDebtByIdRequest.FromString,
                    response_serializer=order__pb2.GetCustomerDebtByIdResponse.SerializeToString,
            ),
            'UpdateCustomerDebtById': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCustomerDebtById,
                    request_deserializer=order__pb2.UpdateCustomerDebtByIdRequest.FromString,
                    response_serializer=order__pb2.UpdateCustomerDebtByIdResponse.SerializeToString,
            ),
            'GetCartByProductId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCartByProductId,
                    request_deserializer=order__pb2.GetCartByProductIdRequest.FromString,
                    response_serializer=order__pb2.GetCartByProductIdResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'order.OrderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OrderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetOrderById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order.OrderService/GetOrderById',
            order__pb2.GetOrderByIdRequest.SerializeToString,
            order__pb2.GetOrderByIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOrderItemById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order.OrderService/GetOrderItemById',
            order__pb2.GetOrderItemByIdRequest.SerializeToString,
            order__pb2.GetOrderItemByIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOrderItemsByProductId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order.OrderService/GetOrderItemsByProductId',
            order__pb2.GetOrderItemsByProductIdRequest.SerializeToString,
            order__pb2.OrderItemsListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCustomerById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order.OrderService/GetCustomerById',
            order__pb2.GetCustomerByIdRequest.SerializeToString,
            order__pb2.GetCustomerByIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOrderItemQuantityByProductId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order.OrderService/GetOrderItemQuantityByProductId',
            order__pb2.GetOrderItemQuantityByProductIdRequest.SerializeToString,
            order__pb2.GetOrderItemQuantityByProductIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOrderItemsByCreatedById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order.OrderService/GetOrderItemsByCreatedById',
            order__pb2.GetOrderItemsByCreatedByIdRequest.SerializeToString,
            order__pb2.OrderItemsListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOrderByCreatedByIdAndPaymentType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order.OrderService/GetOrderByCreatedByIdAndPaymentType',
            order__pb2.GetOrderByCreatedByIdAndPaymentTypeRequest.SerializeToString,
            order__pb2.GetOrderByCreatedByIdAndPaymentTypeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOrderItemsByProductIdAndCreatedById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order.OrderService/GetOrderItemsByProductIdAndCreatedById',
            order__pb2.GetOrderItemsByProductIdAndCreatedByIdRequest.SerializeToString,
            order__pb2.OrderItemsListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllOrderItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order.OrderService/GetAllOrderItems',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            order__pb2.OrderItemsListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllCustomers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order.OrderService/GetAllCustomers',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            order__pb2.CustomerListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCustomersByCreatedBy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order.OrderService/GetCustomersByCreatedBy',
            order__pb2.GetCustomersByCreatedByRequest.SerializeToString,
            order__pb2.GetCustomersByCreatedByResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOrderItemsByOrderId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order.OrderService/GetOrderItemsByOrderId',
            order__pb2.GetOrderItemsByOrderIdRequest.SerializeToString,
            order__pb2.OrderItemsListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateOrderById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order.OrderService/UpdateOrderById',
            order__pb2.UpdateOrderByIdRequest.SerializeToString,
            order__pb2.UpdateOrderByIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveProductFromCartByProductId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order.OrderService/RemoveProductFromCartByProductId',
            order__pb2.RemoveProductFromCartByProductIdRequest.SerializeToString,
            order__pb2.RemoveProductFromCartByProductIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCustomerDebtById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order.OrderService/GetCustomerDebtById',
            order__pb2.GetCustomerDebtByIdRequest.SerializeToString,
            order__pb2.GetCustomerDebtByIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateCustomerDebtById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order.OrderService/UpdateCustomerDebtById',
            order__pb2.UpdateCustomerDebtByIdRequest.SerializeToString,
            order__pb2.UpdateCustomerDebtByIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCartByProductId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order.OrderService/GetCartByProductId',
            order__pb2.GetCartByProductIdRequest.SerializeToString,
            order__pb2.GetCartByProductIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
